---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
      annotations:
        checksum/config: {{ .Files.Get "client_config.json" | sha256sum }}
    spec:
      containers:
        - name: application
          image: gok8
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: /client-config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: client-config